-- MySQL Script generated by MySQL Workbench
-- Thu Aug  6 12:38:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema investmais1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema investmais1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS investmais1 DEFAULT CHARACTER SET utf8 ;
USE investmais1 ;

-- -----------------------------------------------------
-- Table investmais1.perfil
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.perfil (
  idperfil INT NOT NULL,
  desc_perfil VARCHAR(45) NULL,
  PRIMARY KEY (idperfil),
  UNIQUE INDEX idperfil_UNIQUE (idperfil ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table investmais1.Usuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.Usuario (
  idUsuario INT NOT NULL,
  nome VARCHAR(250) NOT NULL,
  email VARCHAR(45) NULL,
  senha VARCHAR(255) NULL,
  perfil_idperfil INT NOT NULL,
  PRIMARY KEY (idUsuario),
  UNIQUE INDEX idUsuario_UNIQUE (idUsuario ASC) ,
  INDEX fk_Usuario_perfil1_idx (perfil_idperfil ASC) ,
  CONSTRAINT fk_Usuario_perfil1
    FOREIGN KEY (perfil_idperfil)
    REFERENCES investmais1.perfil (idperfil)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Usuario do sistema ';


-- -----------------------------------------------------
-- Table investmais1.tp_usuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.tp_usuario (
  idtp_usuario INT NOT NULL,
  desc_tp_usuario VARCHAR(100) NOT NULL,
  PRIMARY KEY (idtp_usuario))
ENGINE = InnoDB
COMMENT = 'Tipo usuario pessoa fisica ou juridica';


-- -----------------------------------------------------
-- Table investmais1.DadosUsuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.DadosUsuario (
  idDadosUsuarioco VARCHAR(45) NOT NULL,
  TelefoneCel VARCHAR(45) NULL,
  telefoneRes VARCHAR(45) NULL,
  Usuario_idUsuario INT NOT NULL,
  tp_usuario_idtp_usuario INT NOT NULL,
  nome_empresa VARCHAR(250) NULL,
  PRIMARY KEY (idDadosUsuarioco),
  UNIQUE INDEX idDadosUsuarioco_UNIQUE (idDadosUsuarioco ASC) ,
  INDEX fk_DadosUsuario_Usuario1_idx (Usuario_idUsuario ASC) ,
  INDEX fk_DadosUsuario_tp_usuario1_idx (tp_usuario_idtp_usuario ASC) ,
  CONSTRAINT fk_DadosUsuario_Usuario1
    FOREIGN KEY (Usuario_idUsuario)
    REFERENCES investmais1.Usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_DadosUsuario_tp_usuario1
    FOREIGN KEY (tp_usuario_idtp_usuario)
    REFERENCES investmais1.tp_usuario (idtp_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table investmais1.tipo_conta
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.tipo_conta (
  idtipo_conta INT NOT NULL AUTO_INCREMENT,
  descConta VARCHAR(45) NULL,
  PRIMARY KEY (idtipo_conta))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table investmais1.InstituicaoFinanceira
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.InstituicaoFinanceira (
  idInstituicaoFinanceira INT NOT NULL AUTO_INCREMENT,
  InstituicaoFinanceiracolDesc VARCHAR(45) NULL,
  tipo_conta_idtipo_conta INT NOT NULL,
  PRIMARY KEY (idInstituicaoFinanceira),
  UNIQUE INDEX idInstituicaoFinanceira_UNIQUE (idInstituicaoFinanceira ASC) ,
  INDEX fk_InstituicaoFinanceira_tipo_conta1_idx (tipo_conta_idtipo_conta ASC) ,
  CONSTRAINT fk_InstituicaoFinanceira_tipo_conta1
    FOREIGN KEY (tipo_conta_idtipo_conta)
    REFERENCES investmais1.tipo_conta (idtipo_conta)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table investmais1.conta
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.conta (
  idconta INT NOT NULL AUTO_INCREMENT,
  Usuario_idUsuario INT NOT NULL,
  InstituicaoFinanceira_idInstituicaoFinanceira INT NOT NULL,
  PRIMARY KEY (idconta, Usuario_idUsuario, InstituicaoFinanceira_idInstituicaoFinanceira),
  UNIQUE INDEX idconta_UNIQUE (idconta ASC) ,
  INDEX fk_conta_Usuario1_idx (Usuario_idUsuario ASC) ,
  INDEX fk_conta_InstituicaoFinanceira1_idx (InstituicaoFinanceira_idInstituicaoFinanceira ASC) ,
  CONSTRAINT fk_conta_Usuario1
    FOREIGN KEY (Usuario_idUsuario)
    REFERENCES investmais1.Usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_conta_InstituicaoFinanceira1
    FOREIGN KEY (InstituicaoFinanceira_idInstituicaoFinanceira)
    REFERENCES investmais1.InstituicaoFinanceira (idInstituicaoFinanceira)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table investmais1.tipocategoria
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.tipocategoria (
  idtipocategoria INT NOT NULL AUTO_INCREMENT,
  idtipocategoriaDesc VARCHAR(45) NULL,
  PRIMARY KEY (idtipocategoria))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table investmais1.categoria
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.categoria (
  idcategoria INT NOT NULL AUTO_INCREMENT,
  categoriaDesc VARCHAR(45) NULL,
  tipocategoria_idtipocategoria INT NOT NULL,
  PRIMARY KEY (idcategoria, tipocategoria_idtipocategoria),
  INDEX fk_categoria_tipocategoria1_idx (tipocategoria_idtipocategoria ASC) ,
  CONSTRAINT fk_categoria_tipocategoria1
    FOREIGN KEY (tipocategoria_idtipocategoria)
    REFERENCES investmais1.tipocategoria (idtipocategoria)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table investmais1.transacao
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS investmais1.transacao (
  idtransacao INT NOT NULL AUTO_INCREMENT,
  categoria_idcategoria INT NOT NULL,
  conta_idconta INT NOT NULL,
  conta_InstituicaoFinanceira_idInstituicaoFinanceira INT NOT NULL,
  PRIMARY KEY (idtransacao),
  INDEX fk_despesas_categoria1_idx (categoria_idcategoria ASC) ,
  INDEX fk_despesas_conta1_idx (conta_idconta ASC, conta_InstituicaoFinanceira_idInstituicaoFinanceira ASC) ,
  CONSTRAINT fk_despesas_categoria1
    FOREIGN KEY (categoria_idcategoria)
    REFERENCES investmais1.categoria (idcategoria)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_despesas_conta1
    FOREIGN KEY (conta_idconta)
    REFERENCES investmais1.conta (idconta)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
